version: 0.1

environment_variables:
  plaintext:
    IMAGE_REPO_NAME: sample_node_ayeaye
    AMAZON_ECR_URL: 288971733297.dkr.ecr.us-east-1.amazonaws.com
    IMAGE_TAG: buildspecTest
    AWS_DEFAULT_REGION: us-east-1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $AMAZON_ECR_URL/$IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AMAZON_ECR_URL/$IMAGE_REPO_NAME:$IMAGE_TAG
