triggers:
  - name: trigger-test-deploy-sample
    type: trigger
    version:
      message: 'trigger for TEST'

  - name: trigger-prod-deploy-sample
    type: trigger
    version:
      message: 'trigger for PROD'
