triggers:
  - name: trigger-test-deploy-sample
    type: trigger
    version:
      message: 'testing trigger in TEST'

triggers:
  - name: trigger-prod-deploy-sample
    type: trigger
    version:
      message: 'testing trigger in PROD'
