jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# add pipeline workflow

# manifest gen for VISUALIZER
  - name: man-sample
    type: manifest
    steps:
      - IN: img-sample
      - IN: img-opts-sample
      - IN: trigger-test-deploy-sample
      - TASK: managed

# TEST deployment to Amazon ECS
  - name: test-ecs-sample
    type: deploy
    steps:
      - IN: man-sample
      - IN: params-sample-test
      - IN: trigger-sample-test
      - IN: env-test-ecs
      - IN: alb-demo-test
        applyTo:
          - manifest: man-sample          #required for load balancer
            image: img-sample             #required for load balancer
            port: 8080                    #required for load balancer
      - TASK: managed

# PROD deployment to Amazon ECS
  - name: prod-ecs-sample
    type: deploy
    steps:
      - IN: test-ecs-sample
      - IN: params-sample-prod
      - IN: replicas-sample-prod
      - IN: alb-demo-prod
      - IN: env-test-ecs
      - IN: trigger-sample-prod
        applyTo:
          - manifest: man-sample        #required for load balancer
            image: img-sample           #required for load balancer
            port: 80                    #required for load balancer
      - TASK: managed
